- name: Install application
  hosts: webservers
  become: true
  vars:
    packages:
      - postfix
      - mariadb-server
  tasks:
  - name: Ensure that packages are installed
    ansible.builtin.yum:
      name: "{{ packages }}"
      state: installed
    tags:  # Tag each task
    - install
  - name: Ensure that packages are absent
    ansible.builtin.yum:
      name: "{{ packages }}"
      state: absent
    tags:  # Tag each task
    - absent
