download_url: https://hub.lab.example.com/api/galaxy/v3/plugin/ansible/content/published/collections/artifacts/example-collection-1.0.0.tar.gz
format_version: 1.0.0
name: collection
namespace: example
server: https://hub.lab.example.com/api/galaxy/content/published/
signatures: []
version: 1.0.0
version_url: /api/galaxy/content/published/v3/plugin/ansible/content/published/collections/index/example/collection/versions/1.0.0/
