---
- name: Using the runonce
  hosts: all
  become: true
  run_once: true
  tasks:
  - name: Install the package 
    ansible.builtin.yum:
      name: 
        - perl
        - postfix 
      state: installed
...
